signature.OnReceive: true
signature.OnSend: true
signature.keyStoreFileName: ./cise-emulator-assembly/src/main/conf/keyStore.jks
signature.keyStorePassword: password
signature.certificateKey: apache.nodecx.eucise.cx
signature.certificatePassword: password
signature.counterpartCertificateKey: simlsa3-nodecx.nodecx.eucise.cx
signature.counterpartCertificateKeyPassword: password


operation.mode: EGN
operation.publishedId: fr.sim-egn
operation.serviceMode: REST
operation.counterpartUrl: http://localhost:18080/sim-EGN/rest/CISEMessageServiceREST
operation.outputDirectory: ./tmp
operation.inputDirectory: ./tmp
operation.sourceMessageDir:  ./cise-emulator-assembly/src/main/conf/xmlmessages
operation.sourcePayloadDir: ./cise-emulator-assembly/src/main/conf/xmlpayloads


server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081


logging:
  level: INFO
  loggers:
    "eu.europa.ec.jrc.marex.cli.clientCustom.Command": INFO
    "eu.europa.ec.jrc.marex.resource.InboundRESTMessageService": INFO
  appenders:
    - type: console
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout