version: '3.3'
services:
  cise-sim:
    image: poaless/cise-sim:latest
    volumes:
      - ./conf:/srv/cise-simulator/conf
      - ./logs:/srv/cise-simulator/logs
      - ./msghistory:/srv/cise-simulator/msghistory
    ports:
      - 8080:8080
      - 8081:8081

