signature.OnReceive: true
signature.OnSend: true
signature.keyStoreFileName: keyStore.jks
signature.keyStorePassword: cisecise
signature.certificateKey: sim1-node01.node01.eucise.fr
signature.certificatePassword: cisecise
signature.counterpartCertificateKey: cisecise
operation.mode : EGN
operation.publishedId: fr.sim-egn
operation.serviceMode: SOAP
operation.counterpartUrl: http://localhost:18080/sim-EGN/rest/CISEMessageServiceREST
operation.outputDirectory: /opt/jboss/EuciseData/
operation.inputDirectory: /opt/jboss/EuciseData/
operation.sourceMessageDir: /opt/jboss/EuciseData/sim-egn/messageXmlFiles
operation.sourcePayloadDir: /opt/jboss/EuciseData/sim-egn/payloadXmlFiles
server:
  applicationConnectors:
    - type: http
      port: 58080
  adminConnectors:
    - type: http
      port: 58081
logging:
  level: INFO
  loggers:
    "eu.europa.ec.jrc.marex.cli.clientCustom.Command": INFO
    "eu.europa.ec.jrc.marex.resource.InboundRESTMessageService": INFO
  appenders:
    - type: console
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      timeZone: UTC
      target: stdout