signature.OnReceive: true
signature.OnSend: true
signature.keyStoreFileName: /opt/jboss/EuciseData/sim-egn/conf/apache-nodecx.jks
signature.keyStorePassword: password
signature.certificateKey: apache.nodecx.eucise.cx
signature.certificatePassword: password
signature.counterpartCertificateKey: simlsa3-nodecx.nodecx.eucise.cx
signature.counterpartCertificateKeyPassword: password

operation.mode: EGN
operation.publishedId: fr.sim-egn
operation.serviceMode: REST
operation.counterpartUrl: http://localhost:8080/sim-LSA/rest/CISEMessageServiceREST
operation.outputDirectory: ./tmp/
operation.inputDirectory: ./tmp/
operation.sourceMessageDir: ./xmlmessages/
operation.sourcePayloadDir: ./xmlpayloads/

server:
  applicationConnectors:
    - type: http
      port: 48080

logging: !<default>
  level: "INFO"
  loggers:
    eu.europa.ec.jrc.marex.cli.clientCustom.Command: "INFO"
    eu.europa.ec.jrc.marex.resource.InboundRESTMessageService: "INFO"
