signature.OnReceive: true
signature.OnSend: true
signature.keyStoreFileName: /home/cise/IdeaProjects/cise-emulator/cise-emulator-app/src/test/resources/remoteDemo/apache-nodecx.jks
signature.keyStorePassword: password
signature.certificateKey: apache.nodecx.eucise.cx
signature.certificatePassword: password
signature.counterpartCertificateKey: simlsa3-nodecx.nodecx.eucise.cx
signature.counterpartCertificateKeyPassword: password

operation.mode: EGN
operation.publishedId: fr.sim-egn
operation.serviceMode: SOAP
operation.counterpartUrl: http://localhost:48080/emu/soap/CISEMessageService?wsdl
operation.outputDirectory: ./tmp/
operation.inputDirectory: ./tmp/
operation.sourceMessageDir: ./xmlmessages/
operation.sourcePayloadDir: ./xmlpayloads/
server:
  applicationConnectors:
    - type: http
      port: 58080
logging: !<default>
  level: "INFO"
  loggers:
    eu.europa.ec.jrc.marex.cli.clientCustom.Command: "INFO"
    eu.europa.ec.jrc.marex.resource.InboundRESTMessageService: "INFO"
