version: '3'
services:
  cise-sim:
    image: ec-jrc/cise-sim:1.3.0
    volumes:
      - ./conf:/srv/cise-simulator/conf
      - ./logs:/srv/cise-simulator/logs
      - ./msghistory:/srv/cise-simulator/msghistory
    ports:
      - 8200:8200
      - 8201:8201

